// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_commit */
export default interface GitCommitTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	oid: ColumnType<Buffer, Buffer, Buffer>

	tree_oid: ColumnType<Buffer, Buffer, Buffer>

	parents: ColumnType<Buffer[], Buffer[], Buffer[]>

	commit_time: ColumnType<string, string, string>

	generation: ColumnType<number | null, number | null, number | null>
}

export type GitCommit = Selectable<GitCommitTable>

export type NewGitCommit = Insertable<GitCommitTable>

export type GitCommitUpdate = Updateable<GitCommitTable>
