// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_edge */
export default interface GitEdgeTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	parent: ColumnType<Buffer, Buffer, Buffer>

	child: ColumnType<Buffer, Buffer, Buffer>

	kind: ColumnType<number, number, number>
}

export type GitEdge = Selectable<GitEdgeTable>

export type NewGitEdge = Insertable<GitEdgeTable>

export type GitEdgeUpdate = Updateable<GitEdgeTable>
