// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_object */
export default interface GitObjectTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	oid: ColumnType<Buffer, Buffer, Buffer>

	type: ColumnType<number, number, number>

	size: ColumnType<number, number, number>

	content: ColumnType<Buffer, Buffer, Buffer>

	created_at: ColumnType<Date, Date | string | undefined, Date | string>
}

export type GitObject = Selectable<GitObjectTable>

export type NewGitObject = Insertable<GitObjectTable>

export type GitObjectUpdate = Updateable<GitObjectTable>
