// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_pack_encoding */
export default interface GitPackEncodingTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	oid: ColumnType<Buffer, Buffer, Buffer>

	base_oid: ColumnType<Buffer | null, Buffer | null, Buffer | null>

	data_size: ColumnType<number, number, number>

	data: ColumnType<Buffer, Buffer, Buffer>
}

export type GitPackEncoding = Selectable<GitPackEncodingTable>

export type NewGitPackEncoding = Insertable<GitPackEncodingTable>

export type GitPackEncodingUpdate = Updateable<GitPackEncodingTable>
