// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Identifier type for public.git_ref */
export type GitRefName = string & { __brand: "public.git_ref" }

/** Represents the table public.git_ref */
export default interface GitRefTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	name: ColumnType<GitRefName, GitRefName, GitRefName>

	oid: ColumnType<Buffer | null, Buffer | null, Buffer | null>

	peeled_oid: ColumnType<Buffer | null, Buffer | null, Buffer | null>

	symref_target: ColumnType<string | null, string | null, string | null>
}

export type GitRef = Selectable<GitRefTable>

export type NewGitRef = Insertable<GitRefTable>

export type GitRefUpdate = Updateable<GitRefTable>
