// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_reach_epoch */
export default interface GitReachEpochTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	epoch: ColumnType<string, string, string>

	tips: ColumnType<Buffer, Buffer, Buffer>

	oids: ColumnType<Buffer, Buffer, Buffer>
}

export type GitReachEpoch = Selectable<GitReachEpochTable>

export type NewGitReachEpoch = Insertable<GitReachEpochTable>

export type GitReachEpochUpdate = Updateable<GitReachEpochTable>
