// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Identifier type for public.git_reach_bitmap */
export type GitReachBitmapTipOid = Buffer & { __brand: "public.git_reach_bitmap" }

/** Represents the table public.git_reach_bitmap */
export default interface GitReachBitmapTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	tip_oid: ColumnType<GitReachBitmapTipOid, GitReachBitmapTipOid, GitReachBitmapTipOid>

	epoch: ColumnType<string, string, string>

	bits: ColumnType<Buffer, Buffer, Buffer>
}

export type GitReachBitmap = Selectable<GitReachBitmapTable>

export type NewGitReachBitmap = Insertable<GitReachBitmapTable>

export type GitReachBitmapUpdate = Updateable<GitReachBitmapTable>
