// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.git_tag */
export default interface GitTagTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	oid: ColumnType<Buffer, Buffer, Buffer>

	target_oid: ColumnType<Buffer, Buffer, Buffer>

	target_type: ColumnType<number, number, number>
}

export type GitTag = Selectable<GitTagTable>

export type NewGitTag = Insertable<GitTagTable>

export type GitTagUpdate = Updateable<GitTagTable>
