// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { PacksId } from "./Packs"

/** Identifier type for public.objects */
export type ObjectsRepoId = string & { __brand: "public.objects" }

/** Identifier type for public.objects */
export type ObjectsOid = string & { __brand: "public.objects" }

/** Represents the table public.objects */
export default interface ObjectsTable {
	repo_id: ColumnType<ObjectsRepoId, ObjectsRepoId, ObjectsRepoId>

	oid: ColumnType<ObjectsOid, ObjectsOid, ObjectsOid>

	pack_id: ColumnType<PacksId, PacksId, PacksId>

	type: ColumnType<string, string, string>

	size: ColumnType<string, string, string>
}

export type Objects = Selectable<ObjectsTable>

export type NewObjects = Insertable<ObjectsTable>

export type ObjectsUpdate = Updateable<ObjectsTable>
