// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.packs */
export type PacksId = string & { __brand: "public.packs" }

/** Represents the table public.packs */
export default interface PacksTable {
	id: ColumnType<PacksId, never, never>

	repo_id: ColumnType<string, string, string>

	checksum: ColumnType<string, string, string>

	created_at: ColumnType<Date, Date | string | undefined, Date | string>

	dead_at: ColumnType<Date | null, Date | string | null, Date | string | null>

	bytes: ColumnType<Buffer, Buffer, Buffer>
}

export type Packs = Selectable<PacksTable>

export type NewPacks = Insertable<PacksTable>

export type PacksUpdate = Updateable<PacksTable>
