// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as GitCommitTable } from "./GitCommit"
import type { default as GitObjectTable } from "./GitObject"
import type { default as GitPackEncodingTable } from "./GitPackEncoding"
import type { default as GitReachBitmapTable } from "./GitReachBitmap"
import type { default as GitReachEpochTable } from "./GitReachEpoch"
import type { default as GitRefTable } from "./GitRef"
import type { default as GitTagTable } from "./GitTag"
import type { default as KyselyMigrationTable } from "./KyselyMigration"
import type { default as KyselyMigrationLockTable } from "./KyselyMigrationLock"
import type { default as RepoFileTable } from "./RepoFile"
import type { default as RepoFileHeadTable } from "./RepoFileHead"
import type { default as ReposTable } from "./Repos"

export default interface PublicSchema {
	kysely_migration_lock: KyselyMigrationLockTable

	git_reach_epoch: GitReachEpochTable

	git_tag: GitTagTable

	git_commit: GitCommitTable

	git_pack_encoding: GitPackEncodingTable

	git_ref: GitRefTable

	repo_file_head: RepoFileHeadTable

	repo_file: RepoFileTable

	kysely_migration: KyselyMigrationTable

	git_reach_bitmap: GitReachBitmapTable

	git_object: GitObjectTable

	repos: ReposTable
}
