// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as KyselyMigrationTable } from "./KyselyMigration"
import type { default as KyselyMigrationLockTable } from "./KyselyMigrationLock"
import type { default as ObjectsTable } from "./Objects"
import type { default as PacksTable } from "./Packs"
import type { default as RefsTable } from "./Refs"

export default interface PublicSchema {
	kysely_migration_lock: KyselyMigrationLockTable

	refs: RefsTable

	objects: ObjectsTable

	kysely_migration: KyselyMigrationTable

	packs: PacksTable
}
