// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.refs */
export type RefsRepoId = string & { __brand: "public.refs" }

/** Identifier type for public.refs */
export type RefsName = string & { __brand: "public.refs" }

/** Represents the table public.refs */
export default interface RefsTable {
	repo_id: ColumnType<RefsRepoId, RefsRepoId, RefsRepoId>

	name: ColumnType<RefsName, RefsName, RefsName>

	oid: ColumnType<string | null, string | null, string | null>

	symref_target: ColumnType<string | null, string | null, string | null>
}

export type Refs = Selectable<RefsTable>

export type NewRefs = Insertable<RefsTable>

export type RefsUpdate = Updateable<RefsTable>
