// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.repo_view_blobs */
export type RepoViewBlobsRepoId = string & { __brand: "public.repo_view_blobs" }

/** Identifier type for public.repo_view_blobs */
export type RepoViewBlobsOid = string & { __brand: "public.repo_view_blobs" }

/** Represents the table public.repo_view_blobs */
export default interface RepoViewBlobsTable {
	repo_id: ColumnType<RepoViewBlobsRepoId, RepoViewBlobsRepoId, RepoViewBlobsRepoId>

	oid: ColumnType<RepoViewBlobsOid, RepoViewBlobsOid, RepoViewBlobsOid>

	content: ColumnType<Buffer, Buffer, Buffer>
}

export type RepoViewBlobs = Selectable<RepoViewBlobsTable>

export type NewRepoViewBlobs = Insertable<RepoViewBlobsTable>

export type RepoViewBlobsUpdate = Updateable<RepoViewBlobsTable>
