// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { RepoViewBlobsOid, RepoViewBlobsRepoId } from "./RepoViewBlobs"

/** Identifier type for public.repo_view_files */
export type RepoViewFilesRefName = string & { __brand: "public.repo_view_files" }

/** Identifier type for public.repo_view_files */
export type RepoViewFilesPath = string & { __brand: "public.repo_view_files" }

/** Represents the table public.repo_view_files */
export default interface RepoViewFilesTable {
	repo_id: ColumnType<RepoViewBlobsRepoId, RepoViewBlobsRepoId, RepoViewBlobsRepoId>

	ref_name: ColumnType<RepoViewFilesRefName, RepoViewFilesRefName, RepoViewFilesRefName>

	path: ColumnType<RepoViewFilesPath, RepoViewFilesPath, RepoViewFilesPath>

	mode: ColumnType<string, string, string>

	blob_oid: ColumnType<RepoViewBlobsOid, RepoViewBlobsOid, RepoViewBlobsOid>
}

export type RepoViewFiles = Selectable<RepoViewFilesTable>

export type NewRepoViewFiles = Insertable<RepoViewFilesTable>

export type RepoViewFilesUpdate = Updateable<RepoViewFilesTable>
