// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Represents the table public.repo_file */
export default interface RepoFileTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	ref_name: ColumnType<string, string, string>

	path: ColumnType<string, string, string>

	mode: ColumnType<string, string, string>

	blob_oid: ColumnType<Buffer, Buffer, Buffer>
}

export type RepoFile = Selectable<RepoFileTable>

export type NewRepoFile = Insertable<RepoFileTable>

export type RepoFileUpdate = Updateable<RepoFileTable>
