// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ReposId } from "./Repos"

/** Identifier type for public.repo_file_head */
export type RepoFileHeadRefName = string & { __brand: "public.repo_file_head" }

/** Represents the table public.repo_file_head */
export default interface RepoFileHeadTable {
	repo_id: ColumnType<ReposId, ReposId, ReposId>

	ref_name: ColumnType<RepoFileHeadRefName, RepoFileHeadRefName, RepoFileHeadRefName>

	commit_oid: ColumnType<Buffer, Buffer, Buffer>
}

export type RepoFileHead = Selectable<RepoFileHeadTable>

export type NewRepoFileHead = Insertable<RepoFileHeadTable>

export type RepoFileHeadUpdate = Updateable<RepoFileHeadTable>
