// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.repos */
export type ReposId = string & { __brand: "public.repos" }

/** Represents the table public.repos */
export default interface ReposTable {
	id: ColumnType<ReposId, never, never>

	name: ColumnType<string, string, string>

	last_pushed_at: ColumnType<Date | null, Date | string | null, Date | string | null>

	last_gc_at: ColumnType<Date | null, Date | string | null, Date | string | null>
}

export type Repos = Selectable<ReposTable>

export type NewRepos = Insertable<ReposTable>

export type ReposUpdate = Updateable<ReposTable>
